### PR TITLE
added new look to polylookup

### PR DESCRIPTION
**Pull request by khoait**
### Previous Behavior
- only classic look with fluent UI v8

### New Behavior
- added new look with fluent UI v9

### Related Issue(s)
- completed #138

### CODE REVIEW

**Comment by wenstarner** [comment]
Hello Khoa! I've been following your repo activity and saw this update so was keen to check it out ASAP 😄 

The new Fluent styling looks great! I was wondering if you might consider making the final styling appear more native?

For example, screenshots below of the new PolyLookup styling and also the native FS multiselect control.

Would you be open to having the selected values look more like the native ones? To blend in better with other controls/components on a form.

For example, the values could:
1. be in blue, with no border (to distinguish from the grey background)
2. have a smaller height, so that the overall row height for a single line is the same as the overall row height for other controls/components (e.g. LookDown)

Just a couple of ideas... 🙂


image

image

**Comment by khoait** [comment]
Hi @wenstarner thanks for your suggestion!

The selected tags will be in blue when the `Tag Action` property is defined (clickable). If the tag is not clickable, it will appear as a normal tag.

regarding the size, using small size the control box is similar to a normal field, but the tag becomes too small I think, please see a sample using small size below

image

**Comment by wenstarner** [comment]
Thanks for pointing that out RE the `Tag Action` property. I hadn't thought of that... I configured that property, and it looks great 🙂

RE sizing, it looks like the text size is actually the same as the native controls--it's just the tag height and control box in LookDown that are taller.

I don't know how to code, otherwise I would have loved to have contributed something directly! The best I can do is to look at the pixels and provide info/feedback.

The first screenshot below shows a comparison between LookDown (the first 'W') and the native lookup (the second 'W'). I've summarised the pixels in this table. It appears that the text in the native control remains the same size as it is in LookDown, despite the control/tag appearing smaller overall. So it's just the box height and the tag height that are different:

| Item| LookDown | Native lookup control |
|--------|--------|--------|
| Box height | 124px | 96px |
| Tag height | 96px | 72px |
| Offset of tag from box (from the top) | 14px | 12px | 
| Text size | 30px | 30px | 

The second screenshot below shows LookDown vs. a native lookup, on a yellow background, to show how the box and the tag are significantly taller. You can see that the text actually is the same height... no change between LookDown and the native control.

So it looks like it would be possible to keep the text at the same size, but to reduce the height of the box overall, and the tag? Am mentioning this as you might like to keep things similarly sized, so that LookDown fits in nicely with other native controls on a form.

Finally, a couple of ideas/questions:
1. Would you consider including an underline for the tag text? So that it is apparent to users that the tag can be clicked to bring up a form for the tag record (native or intersect). And so it complements the style of the native lookup control.
2. In the third image, I've shown the clear tag 'X' in LookDown and the native control. This is pedantic, but I was taking screenshots anyway, so... might you consider bringing your 'X' in line with the native control? So that everything looks like its part of the same design language and fits together on a form.

Thanks again! I hope this helps with getting some feedback 🙂

image

image

image

**Comment by satriotsubasa** [comment]
Hi @khoait , thanks a lot for keep updating these wonderful PCF, after I tried your lookdown, I got interested with your polylookup as well which is really awesome. 

I only have small suggestions here, I'm trying to add countries, i.e after I select Argentina and Andorra, those value are still visible in the lookup dropdown which will allow duplicate inputs:
image

I've handle the duplication issue by adding key and plugin validation but would be good also if it's being handled from the PCF.

Also, I found a minor bug: after clicking the polylookup field on the form, the lookup dropdown couldn't be collapsed by clicking any area in the form, it only collapsed after I re-click again the polylookup field. Maybe something with setfocus need to be set.

Thanks a lot for your great work!

**Comment by khoait** [comment]
@wenstarner thanks for your pixel-perfect investigation! I'll try to make it align with the first party control as close as possible.

@satriotsubasa thanks for reporting! I'll check again.

**Comment by khoait** [comment]
@wenstarner @satriotsubasa completed in #157 and will be included in the next release

**Comment by wenstarner** [comment]
That's incredible! Thanks so much @khoait, and I'd also like to say thank you so much always for being willing to consider feedback and suggestions 🙂

**Pull request merged**
